# .github/workflows/deploy.yml
name: Build & Deploy inzva-AI

on:
  push:
    branches: [main]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          # We map the github variable to an env variable first
          IMAGE_PATH: ghcr.io/${{ github.repository }}/inzva-ai-api:latest
        run: |
          # Use ${VAR,,} to lowercase the string in bash
          LOWER_IMAGE_PATH=${IMAGE_PATH,,}
          
          docker build -t $LOWER_IMAGE_PATH .
          docker push $LOWER_IMAGE_PATH
    
